# Generated by Django 4.2.3 on 2023-11-27 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_buyer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producat',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seller'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='producat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='ITI Township, Bengaluru', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(default='Archana Reddy P', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='+91 8171415434', max_length=15),
        ),
    ]
